### ISSUE TITLE
coq 8.5beta2 - cannot guess decreasing argument of fix.

### ISSUE THREAD

**Issue by wesen** [clarus/coq-chick-blog#7]
Using coq 8.5 beta2 (which got installed when using opam, compilation failed in src/Extraction.v:

```
"coqc"  -q  -R "src" ChickBlog   src/Extraction
File "./src/Extraction.v", line 98, characters 0-1002:
Error: Cannot guess decreasing argument of fix.
make: *** [src/Extraction.vo] Error 1
```

I'm an absolute beginner at coq so can't help much further.

**Comment by clarus** [comment]
Thanks! We developed ChickBlog for Coq 8.4 but did not test it for the new Coq 8.5. I commited fixes, now it should work.

**Comment by wesen** [comment]
thank you!
